# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: John Clema
email: john.clema@gmail.com
description: "Hey, thanks for visiting, I am a software developer passionate about
all things travel and coding. I'm particularly interested in iOS development
and ruby at the moment. Feel free to reach out if you have any queries"
baseurl: "" # the subpath of your site, e.g. /blog
url: "johnclema.github.io" # the base hostname & protocol for your site
baseurl: ""
permalink: /:title
twitter_username: JohnClema
github_username:  JohnClema

# Build settings
markdown: kramdown
